# -*- coding: utf-8 -*-
"""MEETING MINUTES GENERATOR

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GwqIqbdFUS0wAzKgN7W_0lDMlBccXAdl
"""

import pandas as pd
from datetime import datetime

print("MEETING MINUTES GENERATOR\n")

#user inputs
meeting_title = input("enter meeting title: ")
date = input("enter meeting date(DD/MM/YYYY):")
time = input("enter meeting time:")
participants = input("enter participants (comma separated):")
agenda = input("enter agenda points (comma separated):")
decisions = input("enter decisions taken (comma separated):")
action_items = input("enter action items (comma separated):")
prepared_by = input("prepared by:")

#process inputs
participants_list = [p.strip() for p in participants.split(",") if p.strip()]
agenda_list = [a.strip() for a in agenda.split(",") if a.strip()]
decisions_list = [d.strip() for d in decisions.split(",") if d.strip()]
action_items_list = [a.strip() for a in action_items.split(",") if a.strip()]

#create structured meeting minutes