# -*- coding: utf-8 -*-
"""PYTHON LIST

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LUOn6P76EaQTocNkrO5XqrxQLDQ27AHY
"""

import time
import sys

size = 1_000_000 # change if needed

# creat large python list
python_list = (range(size))

#Measure execution time
start = time.time()
result = [x*2 for x in python_list]
end = time.time()

print("python List Time:", end - start,"seconds")
print("python List Memory:",sys.getsizeof(python_list),"bytes")