# -*- coding: utf-8 -*-
"""STUDENT AVERAGE MARKS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10uQbkf9EQpnB7LYtlTkx4IGNfRECXDb7
"""

# Data
names = ["Ali","Sara","John","Emma"]
marks = [85,90,78,88]

#Average marks
average = sum(marks)/len(marks)
print("Average marks:",average)

#students with marks>80
print("Students with marks>80:")
for i in range(len(marks)):
  if marks[i]>80:
    print(names[i],marks[i])

    #students with marks >average