# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TZ5tndl_gAllOr_YEYJpwwit0nX6Tc0K
"""

!pip install transformers torch

from transformers import pipeline
# load text generation model (GenAI)
generator = pipeline(
    'text-generation',
    model='gpt2'
)
# input promt
promt=" artificial Intelligence in finance will"

# generate text
result = generator(promt, max_length=50,num_return_sequences=1)

print("AI Generated Text:")
print(result[0]['generated_text'])

from sentence_transformers import SentenceTransformer,util

# Load the model

#Take input from user
text1 = input ("Enter text 1: ")
text2 = input ("Enter text 2: ")

# convert text to embeddings
embedding1 = model.encode(text1)
embedding2 = model.encode(text2)

#calculate similarity
similarity=util.cos_sim(embedding1,embedding2)

#show result
print("\nsimilarity score:",round(float(similarity),2))
if similarity > 0.75:
  print("similarity level : High")
elif similarity > 0.4:
  print("similarity level : Medium")
else:
  print("similarity level : low")